### ISSUE TITLE
🐞 Latest versions unpublished?

### ISSUE THREAD

**Issue by k3n** [deliveryhero/pipeline#7]
**Describe the bug**
It seems that the last published version for this project is `v1.0.0`.

**To Reproduce**
1. Run `GOPROXY= go list -m -versions github.com/deliveryhero/pipeline`
2. Observe that `v1.0.0` is the most recent.

**Expected behavior**
It would reflect up to the latest version, `v2.1.1`.

**Console output**
```bash
$ GOPROXY= go list -m -versions github.com/deliveryhero/pipeline
github.com/deliveryhero/pipeline v0.1.0 v0.2.0 v0.2.1 v0.2.2 v0.2.3 v0.3.0 v0.3.1 v0.4.0 v1.0.0
```

**Client info (please complete the following information):**
 - Device: MacOS
 - OS: Ventura
 - Version: 13.4.1 (c)
 - go version go1.20.5 darwin/amd64

**Additional context**
I am very new to Go and may very well be doing something wrong!

**Comment by marksalpeter** [comment]
No sure when this was opened, but v2.1.1 has been published for a while. [See the releases](https://github.com/deliveryhero/pipeline/releases)

**Comment by k3n** [comment]
Ok, it looks like I need to use `github.com/deliveryhero/pipeline/v2` for the v2 versions (make sense, I just wasn't aware it existed).

```sh
$ GOPROXY= go list -m -versions github.com/deliveryhero/pipeline/v2
github.com/deliveryhero/pipeline/v2 v2.0.0 v2.1.0 v2.1.1 v2.2.0
```

Thanks!
